src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Repository\OperationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OperationRepository::class)]
class Operation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'operations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Adresse $adresse = null;

    #[ORM\ManyToOne(inversedBy: 'operations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Client $client = null;

    #[ORM\ManyToOne(inversedBy: 'operations')]
    private ?User $user = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description_op = null;

    #[ORM\Column(length: 30)]
    private ?string $status = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description_client = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img = null;



    #[ORM\Column(type: Types::FLOAT, nullable: true)]
    private ?float $tarif = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_demande = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdresse(): ?Adresse
    {
        return $this->adresse;
    }

    public function setAdresse(?Adresse $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getDescriptionOp(): ?string
    {
        return $this->description_op;
    }

    public function setDescriptionOp(?string $description_op): static
    {
        $this->description_op = $description_op;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getDescriptionClient(): ?string
    {
        return $this->description_client;
    }

    public function setDescriptionClient(?string $description_client): static
    {
        $this->description_client = $description_client;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): static
    {
        $this->img = $img;

        return $this;
    }

    public function getTarif(): ?float
    {
        return $this->tarif;
    }

    public function setTarif(float $tarif): static
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getDateDemande(): ?\DateTimeInterface
    {
        return $this->date_demande;
    }

    public function setDateDemande(\DateTimeInterface $date_demande): static
    {
        $this->date_demande = $date_demande;

        return $this;
    }
}

src/Controller/TableOpTermineesController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\UserRepository;
use App\Repository\ClientRepository;
use App\Repository\OperationRepository;

class TableOpTermineesController extends AbstractController
{
    #[Route('/table/op/terminees', name: 'app_table_op_terminees')]
    public function table_op_termineesIndex(ClientRepository $clientRepository, OperationRepository $operationRepository): Response
    {
        $clients = $clientRepository->findAll();
        $operations = $operationRepository->findAll();
        $stockOperation = $operationRepository->findAll();

        // Tri des opérations par le nom du client
        usort($operations, function ($a, $b) {
            return strcmp($a->getClient()->getNom(), $b->getClient()->getNom());
        });
    
        $operationDetails = [];
    
        foreach ($operations as $operation) {
            $user = $operation->getUser(); 
            $operationDetails[] = [
                'nom_utilisateur' => $user ? $user->getNom() : 'Utilisateur inconnu',
            ];
        }
    
        return $this->render('table_op_terminees/index.html.twig', [
            'clients' => $clients,
            'operations' => $stockOperation,
            'operationDetails' => $operationDetails,
            'operations'=> $operations,
        ]);
    }
    }



?>

templates/table_op_terminees/index.html.twig
{% block body %}

	<div class="container-fluid">
		<table class="table table-hover table-striped border-2 mt-5">
			<thead>
				<tr>
					<th class="center-table" scope="col">NOM CLIENT</th>
					<th class="center-table" scope="col">PRENOM CLIENT</th>
					<th class="center-table" scope="col">ADRESSE</th>
					<th class="center-table" scope="col">CP</th>
					<th class="center-table" scope="col">VILLE</th>
					<th class="center-table" scope="col">TARIF</th>
					<th class="center-table" scope="col">DATE</th>
					<th class="center-table" scope="col">INTERVENANT</th>
					<th class="center-table" scope="col">FACTURE PDF</th>
					<th class="center-table" scope="col">FACTURE PAR MAIL</th>
				</tr>
			</thead>
			<tbody>
				{% for operation in operations %}
					{% if operation.status == "Terminer" %}
						<tr style="height: 3.125rem;">
							<td class="center-table">{{ operation.client.nom }}</td>
							<td class="center-table">{{ operation.client.prenom }}</td>
							<td class="center-table">{{ operation.adresse.getNRue() }}
								{{ operation.adresse.getNomRue() }}</td>
							<td class="center-table">{{ operation.adresse.cp }}</td>
							<td class="center-table">{{ operation.adresse.getNomVille }}</td>
							<td class="center-table">{{ operation.tarif }}</td>
							<td class="center-table">{{ operation.dateCreation ? operation.dateCreation|date('Y-m-d') }}</td>
							<td class="center-table">{{ operation.user.nom }}
								{{operation.user.prenom}}</td>
							<td class="center-table">
								<a href="{{ path('app_generate_pdf', {'id': operation.id}) }}" class="btn btn-style btn-block">PDF</a>
							</td>
							<td class="center-table">
								<a href="{{ path('app_generate_pdf_and_send_email', {'id': operation.id}) }}" class="btn btn-style btn-block">Par mail</a>
							</td>

						</tr>
					{% endif %}
				{% endfor %}
			</tbody>
		</table>
	</div>

{% endblock %}